-- MySQL Script generated by MySQL Workbench
-- Sun Jun 13 15:05:09 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gowl
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gowl
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gowl` DEFAULT CHARACTER SET utf8 ;
USE `gowl` ;

-- -----------------------------------------------------
-- Table `gowl`.`tb_leitores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gowl`.`tb_leitores` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `rg` VARCHAR(30) NULL DEFAULT NULL,
  `cpf` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(200) NULL DEFAULT NULL,
  `telefone` VARCHAR(30) NULL DEFAULT NULL,
  `celular` VARCHAR(30) NULL DEFAULT NULL,
  `cep` VARCHAR(100) NULL DEFAULT NULL,
  `endereco` VARCHAR(255) NULL DEFAULT NULL,
  `numero` VARCHAR(50) NULL DEFAULT NULL,
  `complemento` VARCHAR(200) NULL DEFAULT NULL,
  `bairro` VARCHAR(100) NULL DEFAULT NULL,
  `cidade` VARCHAR(100) NULL DEFAULT NULL,
  `estado` VARCHAR(2) NULL DEFAULT NULL,
  `tipo` VARCHAR(15) NULL,
  `is_locked` TINYINT NULL,
  `curso` VARCHAR(45) NULL,
  `curso_ano` VARCHAR(45) NULL,
  `qtd_emprestimos` INT(3) NULL,
  `emprestmax` INT NULL,
  `observacoes` VARCHAR(225) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gowl`.`tb_fornecedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gowl`.`tb_fornecedores` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL DEFAULT NULL,
  `cnpj` VARCHAR(100) NULL DEFAULT NULL,
  `email` VARCHAR(200) NULL DEFAULT NULL,
  `telefone` VARCHAR(30) NULL DEFAULT NULL,
  `celular` VARCHAR(30) NULL DEFAULT NULL,
  `cep` VARCHAR(100) NULL DEFAULT NULL,
  `endereco` VARCHAR(255) NULL DEFAULT NULL,
  `numero` VARCHAR(50) NULL DEFAULT NULL,
  `complemento` VARCHAR(200) NULL DEFAULT NULL,
  `bairro` VARCHAR(100) NULL DEFAULT NULL,
  `cidade` VARCHAR(100) NULL DEFAULT NULL,
  `estado` VARCHAR(2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gowl`.`tb_funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gowl`.`tb_funcionarios` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `rg` VARCHAR(30) NULL,
  `cpf` VARCHAR(20) NULL,
  `email` VARCHAR(200) NULL,
  `senha` VARCHAR(10) NOT NULL,
  `cargo` VARCHAR(100) NOT NULL,
  `nivel_acesso` VARCHAR(50) NOT NULL,
  `telefone` VARCHAR(30) NULL,
  `celular` VARCHAR(30) NULL,
  `cep` VARCHAR(100) NOT NULL,
  `endereco` VARCHAR(255) NULL,
  `numero` VARCHAR(50) NULL,
  `complemento` VARCHAR(200) NULL,
  `bairro` VARCHAR(100) NULL,
  `cidade` VARCHAR(100) NOT NULL,
  `estado` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gowl`.`tb_livros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gowl`.`tb_livros` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `autor` VARCHAR(45) NOT NULL,
  `editora` VARCHAR(45) NOT NULL,
  `isbn` VARCHAR(13) NOT NULL,
  `ano` VARCHAR(4) NOT NULL,
  `serie` VARCHAR(45) NULL,
  `edicao` VARCHAR(45) NULL,
  `idioma` VARCHAR(25) NOT NULL,
  `tb_fornecedores_id` INT(11) NULL,
  `piso` VARCHAR(45) NULL,
  `corredor` VARCHAR(45) NULL,
  `posicao` VARCHAR(45) NULL,
  `secao` VARCHAR(45) NULL,
  `disponibilidade` VARCHAR(15) NOT NULL,
  `observacoes` VARCHAR(225) NULL,
  `is_emprestado` TINYINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_livros_tb_fornecedores1_idx` (`tb_fornecedores_id` ASC),
  CONSTRAINT `fk_tb_livros_tb_fornecedores1`
    FOREIGN KEY (`tb_fornecedores_id`)
    REFERENCES `gowl`.`tb_fornecedores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gowl`.`tb_emprestimos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gowl`.`tb_emprestimos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `data_emprestimo` DATETIME NULL,
  `data_devolucao` DATETIME NULL DEFAULT NULL,
  `observacoes` TEXT NULL DEFAULT NULL,
  `tb_funcionarios_id` INT(11) NULL,
  `tb_livros_id` INT(11) NULL,
  `tb_livros_tb_fornecedores_id` INT(11) NULL,
  `tb_leitores_id` INT(11) NULL,
  `data_entrega_agendada` DATETIME NULL,
  `tb_funcionarios_iddevol` INT(11) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_emprestimos_tb_funcionarios1_idx` (`tb_funcionarios_id` ASC),
  INDEX `fk_tb_emprestimos_tb_livros1_idx` (`tb_livros_id` ASC, `tb_livros_tb_fornecedores_id` ASC),
  INDEX `fk_tb_emprestimos_tb_leitores1_idx` (`tb_leitores_id` ASC),
  INDEX `fk_tb_emprestimos_tb_funcionarios2_idx` (`tb_funcionarios_iddevol` ASC),
  CONSTRAINT `fk_tb_emprestimos_tb_funcionarios1`
    FOREIGN KEY (`tb_funcionarios_id`)
    REFERENCES `gowl`.`tb_funcionarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_emprestimos_tb_livros1`
    FOREIGN KEY (`tb_livros_id`)
    REFERENCES `gowl`.`tb_livros` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_emprestimos_tb_leitores1`
    FOREIGN KEY (`tb_leitores_id`)
    REFERENCES `gowl`.`tb_leitores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_emprestimos_tb_funcionarios2`
    FOREIGN KEY (`tb_funcionarios_iddevol`)
    REFERENCES `gowl`.`tb_funcionarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gowl`.`tb_multa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gowl`.`tb_multa` (
  `idmulta` INT NOT NULL AUTO_INCREMENT,
  `dias_atraso` INT(6) NOT NULL,
  `valor_multa` DECIMAL(10,2) NULL,
  `esta_pago` TINYINT NULL,
  `tb_leitores_id` INT(11) NOT NULL,
  `tb_emprestimos_id` INT(11) NOT NULL,
  PRIMARY KEY (`idmulta`, `tb_emprestimos_id`),
  INDEX `fk_multa_tb_leitores1_idx` (`tb_leitores_id` ASC),
  INDEX `fk_tb_multa_tb_emprestimos1_idx` (`tb_emprestimos_id` ASC),
  CONSTRAINT `fk_multa_tb_leitores1`
    FOREIGN KEY (`tb_leitores_id`)
    REFERENCES `gowl`.`tb_leitores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_multa_tb_emprestimos1`
    FOREIGN KEY (`tb_emprestimos_id`)
    REFERENCES `gowl`.`tb_emprestimos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gowl`.`tb_opcoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gowl`.`tb_opcoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` VARCHAR(45) NOT NULL,
  `parentid` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Opcoes_Opcoes1_idx` (`parentid` ASC),
  CONSTRAINT `fk_Opcoes_Opcoes1`
    FOREIGN KEY (`parentid`)
    REFERENCES `gowl`.`tb_opcoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `gowl`.`tb_leitores`
-- -----------------------------------------------------
START TRANSACTION;
USE `gowl`;
INSERT INTO `gowl`.`tb_leitores` (`id`, `nome`, `rg`, `cpf`, `email`, `telefone`, `celular`, `cep`, `endereco`, `numero`, `complemento`, `bairro`, `cidade`, `estado`, `tipo`, `is_locked`, `curso`, `curso_ano`, `qtd_emprestimos`, `emprestmax`, `observacoes`) VALUES (1, 'Leitor 1', '111.111.111-1', '111.111.111-11', 'leitor@test.com', '(42)99999-9999', '(42)99999-9999', '84570-000', 'Rua Tal', '100', 'casa', 'Centro', 'Mallet', 'PR', 'Estudante', 0, 'Letras Ingles / Noturno', '4', 0, 3, 'leitor ok - primeiro cadastro - cadastro completo');
INSERT INTO `gowl`.`tb_leitores` (`id`, `nome`, `rg`, `cpf`, `email`, `telefone`, `celular`, `cep`, `endereco`, `numero`, `complemento`, `bairro`, `cidade`, `estado`, `tipo`, `is_locked`, `curso`, `curso_ano`, `qtd_emprestimos`, `emprestmax`, `observacoes`) VALUES (2, 'Leitor numero 2', '123.123.123-3', '123.123.123-23', 'leitor2@leitor2.com', '(42)98988-8989', '(42)45355-6666', '84570-000', 'Rua 2', '1212', 'Casa', 'Centro', 'Mallet', 'PR', 'Professor', 0, 'Letras', '0', 0, 0, 'Professor - emprestimos ilimitados');

COMMIT;


-- -----------------------------------------------------
-- Data for table `gowl`.`tb_fornecedores`
-- -----------------------------------------------------
START TRANSACTION;
USE `gowl`;
INSERT INTO `gowl`.`tb_fornecedores` (`id`, `nome`, `cnpj`, `email`, `telefone`, `celular`, `cep`, `endereco`, `numero`, `complemento`, `bairro`, `cidade`, `estado`) VALUES (1, 'Fornecedor Teste', '111.111.111/0001-11', 'teste@test', '423232123123', NULL, '84570-000', 'Rua Fccinal', '00', 'Predio', NULL, 'Mallet', 'PR');

COMMIT;


-- -----------------------------------------------------
-- Data for table `gowl`.`tb_funcionarios`
-- -----------------------------------------------------
START TRANSACTION;
USE `gowl`;
INSERT INTO `gowl`.`tb_funcionarios` (`id`, `nome`, `rg`, `cpf`, `email`, `senha`, `cargo`, `nivel_acesso`, `telefone`, `celular`, `cep`, `endereco`, `numero`, `complemento`, `bairro`, `cidade`, `estado`) VALUES (1, 'Administrador', '7.275.275-1', '033.330.003-13', 'admin@admin', 'admin', 'Administrador', 'Administrador', '(42)99987-6543', '123123123123', '84570-000', 'rua Miguel Grenteski', '13', 'Casa', 'Eldorado', 'Mallet', 'PR');

COMMIT;


-- -----------------------------------------------------
-- Data for table `gowl`.`tb_livros`
-- -----------------------------------------------------
START TRANSACTION;
USE `gowl`;
INSERT INTO `gowl`.`tb_livros` (`id`, `titulo`, `autor`, `editora`, `isbn`, `ano`, `serie`, `edicao`, `idioma`, `tb_fornecedores_id`, `piso`, `corredor`, `posicao`, `secao`, `disponibilidade`, `observacoes`, `is_emprestado`) VALUES (1, 'Alice no Pais das Maravilhas', 'Lewis Carrol', 'Dumi Edit', '1234567890123', '1894', 'Especial', '25', 'Portugues', 1, '1', 'b', 'a3', 'Literatura Universal', '1', 'ok', NULL);
INSERT INTO `gowl`.`tb_livros` (`id`, `titulo`, `autor`, `editora`, `isbn`, `ano`, `serie`, `edicao`, `idioma`, `tb_fornecedores_id`, `piso`, `corredor`, `posicao`, `secao`, `disponibilidade`, `observacoes`, `is_emprestado`) VALUES (2, 'A Revolução dos Bichos', 'George Orwell', 'Dumi Edit', '0987654321234', '1934', 'Must be Read Books', '2', 'Portugues', 1, '1', 'b', 'a3', 'Literatura Universal', '3', 'ok', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `gowl`.`tb_opcoes`
-- -----------------------------------------------------
START TRANSACTION;
USE `gowl`;
INSERT INTO `gowl`.`tb_opcoes` (`id`, `data`, `parentid`) VALUES (1, 'piso', NULL);
INSERT INTO `gowl`.`tb_opcoes` (`id`, `data`, `parentid`) VALUES (2, 'corredor', NULL);
INSERT INTO `gowl`.`tb_opcoes` (`id`, `data`, `parentid`) VALUES (3, 'secao', NULL);
INSERT INTO `gowl`.`tb_opcoes` (`id`, `data`, `parentid`) VALUES (4, 'posicao', NULL);
INSERT INTO `gowl`.`tb_opcoes` (`id`, `data`, `parentid`) VALUES (5, 'disponibilidade', NULL);
INSERT INTO `gowl`.`tb_opcoes` (`id`, `data`, `parentid`) VALUES (6, 'printerurl', NULL);
INSERT INTO `gowl`.`tb_opcoes` (`id`, `data`, `parentid`) VALUES (7, 'instituicaonome', NULL);
INSERT INTO `gowl`.`tb_opcoes` (`id`, `data`, `parentid`) VALUES (8, 'instiuicaoendereco', NULL);
INSERT INTO `gowl`.`tb_opcoes` (`id`, `data`, `parentid`) VALUES (17, 'piso 1', 1);
INSERT INTO `gowl`.`tb_opcoes` (`id`, `data`, `parentid`) VALUES (20, 'corredor 1', 2);
INSERT INTO `gowl`.`tb_opcoes` (`id`, `data`, `parentid`) VALUES (21, '1A', 3);
INSERT INTO `gowl`.`tb_opcoes` (`id`, `data`, `parentid`) VALUES (22, 'Literatura Universal', 4);
INSERT INTO `gowl`.`tb_opcoes` (`id`, `data`, `parentid`) VALUES (13, '0', 5);
INSERT INTO `gowl`.`tb_opcoes` (`id`, `data`, `parentid`) VALUES (14, '3', 5);
INSERT INTO `gowl`.`tb_opcoes` (`id`, `data`, `parentid`) VALUES (15, 'Biblioteca de Hogwarts', 7);
INSERT INTO `gowl`.`tb_opcoes` (`id`, `data`, `parentid`) VALUES (16, 'Rua Epsilon, 888, Cidade Imaginaria, LA ', 8);
INSERT INTO `gowl`.`tb_opcoes` (`id`, `data`, `parentid`) VALUES (9, 'tiposdeusuarios', NULL);
INSERT INTO `gowl`.`tb_opcoes` (`id`, `data`, `parentid`) VALUES (18, 'Estudante', 9);
INSERT INTO `gowl`.`tb_opcoes` (`id`, `data`, `parentid`) VALUES (19, 'Professor', 9);
INSERT INTO `gowl`.`tb_opcoes` (`id`, `data`, `parentid`) VALUES (10, 'server url', NULL);
INSERT INTO `gowl`.`tb_opcoes` (`id`, `data`, `parentid`) VALUES (11, 'libraryname', NULL);
INSERT INTO `gowl`.`tb_opcoes` (`id`, `data`, `parentid`) VALUES (12, 'libraryAddress', NULL);
INSERT INTO `gowl`.`tb_opcoes` (`id`, `data`, `parentid`) VALUES (23, '127.0.0.1', 12);
INSERT INTO `gowl`.`tb_opcoes` (`id`, `data`, `parentid`) VALUES (24, 'Nome da Biblioteca', NULL);
INSERT INTO `gowl`.`tb_opcoes` (`id`, `data`, `parentid`) VALUES (25, 'valor_multa', NULL);
INSERT INTO `gowl`.`tb_opcoes` (`id`, `data`, `parentid`) VALUES (26, '300', 25);

COMMIT;

