/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//mude para vizualizacao por projeto para adicionar action
package br.com.projeto.view;

import br.com.projeto.dao.FornecedorDao;
import br.com.projeto.dao.FuncionarioDao;
import br.com.projeto.dao.LivroDao;
import br.com.projeto.dao.OptionsDao;
import br.com.projeto.model.Fornecedor;
import br.com.projeto.model.Livro;
import br.com.projeto.model.Options;
import br.com.projeto.model.Utilitarios;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Everton Luiz Kozloski - evertonkozloski@hotmail.com
 */
public class FormLivros extends javax.swing.JFrame {

    public void LimpaCampos() {
        boxCorredor.removeAllItems();
        boxDisponibilidade.removeAllItems();
        boxFornecedor.removeAllItems();
        boxPiso.removeAllItems();
        boxSecao.removeAllItems();
        boxPosicao.removeAllItems();
    }

    //metodo listar usuarios pt3
    public void listarLivros() throws Exception {
        LivroDao dao = new LivroDao();
        List<Livro> lista = dao.buscarLivros();
        DefaultTableModel dados = (DefaultTableModel) tabelaLivros.getModel();
        dados.setNumRows(0);
        for (Livro c : lista) {
            dados.addRow(new Object[]{
                c.getId(),
                c.getTitulo(),
                c.getAutor(),
                c.getEditora(),
                c.getIsbn(),
                c.getAno(),
                c.getSerie(),
                c.getEdicao(),
                c.getIdioma(),
                c.getFornecedor().getNome(),
                c.getPiso(),
                c.getCorredor(),
                c.getPosicao(),
                c.getSecao(),
                c.getDisponibilidade(),
                c.getObservacoes(),});
        }

    }

    /**
     * Creates new form formLeitor
     */
    public FormLivros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tabbedFrameF = new javax.swing.JTabbedPane();
        tabConsultaUsuarios = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtPesquisaLivros = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaLivros = new javax.swing.JTable();
        tabCadastro = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblAutor = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblAno = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblEditora = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblIsbn = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblEdicao = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtAutor = new javax.swing.JTextField();
        txtEditora = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        boxSecao = new javax.swing.JComboBox<>();
        txtIsbn = new javax.swing.JFormattedTextField();
        jSeparator2 = new javax.swing.JSeparator();
        boxCorredor = new javax.swing.JComboBox<>();
        boxPiso = new javax.swing.JComboBox<>();
        boxPosicao = new javax.swing.JComboBox<>();
        btnMapa = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btNavegar = new javax.swing.JButton();
        btnbaixarCapa = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        txtSerie = new javax.swing.JTextField();
        txtIdioma = new javax.swing.JTextField();
        txtEdicao = new javax.swing.JTextField();
        boxFornecedor = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaObservacoes = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        boxDisponibilidade = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        lblImagem = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtAno = new javax.swing.JFormattedTextField();
        btnSalvar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de Livros");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
        );

        tabConsultaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabConsultaUsuariosMouseClicked(evt);
            }
        });

        jLabel14.setText("Nome:");

        txtPesquisaLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaLivrosActionPerformed(evt);
            }
        });
        txtPesquisaLivros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaLivrosKeyReleased(evt);
            }
        });

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        btnPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnPesquisarKeyReleased(evt);
            }
        });

        tabelaLivros.setAutoCreateRowSorter(true);
        tabelaLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "cod", "Título", "Autor", "Editora", "ISBN", "Ano", "Serie", "Edição", "Idioma", "Fornecedor", "Piso", "Corredor", "Posição", "Seção", "Disponibilidade", "Observações"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaLivros.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabelaLivros.getTableHeader().setReorderingAllowed(false);
        tabelaLivros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaLivrosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaLivros);
        tabelaLivros.getColumn(tabelaLivros.getColumnName(0)).setPreferredWidth(30);
        tabelaLivros.getColumn(tabelaLivros.getColumnName(1)).setPreferredWidth(200);

        javax.swing.GroupLayout tabConsultaUsuariosLayout = new javax.swing.GroupLayout(tabConsultaUsuarios);
        tabConsultaUsuarios.setLayout(tabConsultaUsuariosLayout);
        tabConsultaUsuariosLayout.setHorizontalGroup(
            tabConsultaUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabConsultaUsuariosLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(tabConsultaUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabConsultaUsuariosLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(tabConsultaUsuariosLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPesquisaLivros, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPesquisar)
                        .addGap(426, 426, 426))))
        );
        tabConsultaUsuariosLayout.setVerticalGroup(
            tabConsultaUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabConsultaUsuariosLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(tabConsultaUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtPesquisaLivros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        tabbedFrameF.addTab("Consulta de Livros", tabConsultaUsuarios);

        jLabel2.setText("ID:");

        lblNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblNome.setText("*Título:");

        lblAutor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblAutor.setText("*Autor:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("LOCALIZAÇÃO");

        lblAno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblAno.setText("*Ano:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Posição:");

        lblEditora.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblEditora.setText("*Editora:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("*Seção:");

        lblIsbn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblIsbn.setText("*ISBN:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Corredor:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Piso:");

        lblEdicao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblEdicao.setText("Edição:");

        txtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloActionPerformed(evt);
            }
        });

        txtId.setEditable(false);
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        jLabel19.setText("Série:");

        boxSecao.setBorder(null);
        boxSecao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boxSecaoMouseClicked(evt);
            }
        });

        try {
            txtIsbn.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#############")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jSeparator2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        boxCorredor.setBorder(null);
        boxCorredor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boxCorredorMouseClicked(evt);
            }
        });

        boxPiso.setBorder(null);
        boxPiso.setLightWeightPopupEnabled(false);
        boxPiso.setName(""); // NOI18N
        boxPiso.setRequestFocusEnabled(false);
        boxPiso.setVerifyInputWhenFocusTarget(false);
        boxPiso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boxPisoMouseClicked(evt);
            }
        });

        boxPosicao.setBorder(null);
        boxPosicao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boxPosicaoMouseClicked(evt);
            }
        });

        btnMapa.setText("mapa");
        btnMapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMapaActionPerformed(evt);
            }
        });

        jSeparator1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btNavegar.setText("Navegar");
        btNavegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNavegarActionPerformed(evt);
            }
        });

        btnbaixarCapa.setText("baixar capa");

        jLabel20.setText("*Idioma:");

        txtIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdiomaActionPerformed(evt);
            }
        });

        boxFornecedor.setBorder(null);
        boxFornecedor.setLightWeightPopupEnabled(false);
        boxFornecedor.setOpaque(false);
        boxFornecedor.setVerifyInputWhenFocusTarget(false);
        boxFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boxFornecedorMouseClicked(evt);
            }
        });

        txtAreaObservacoes.setColumns(20);
        txtAreaObservacoes.setRows(5);
        jScrollPane2.setViewportView(txtAreaObservacoes);

        jLabel4.setText("Observações:");

        boxDisponibilidade.setBorder(null);
        boxDisponibilidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boxDisponibilidadeMouseClicked(evt);
            }
        });

        jLabel6.setText("Disponibilidade:");

        lblImagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/book_cover.png"))); // NOI18N
        lblImagem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setText("Alterar Fornecedor:");

        try {
            txtAno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnSalvar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/save_small.png"))); // NOI18N
        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnNovo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/new_file_small.png"))); // NOI18N
        btnNovo.setText("NOVO");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/delete_small.png"))); // NOI18N
        btnExcluir.setText("EXCLUIR");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabCadastroLayout = new javax.swing.GroupLayout(tabCadastro);
        tabCadastro.setLayout(tabCadastroLayout);
        tabCadastroLayout.setHorizontalGroup(
            tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCadastroLayout.createSequentialGroup()
                .addGroup(tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabCadastroLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(lblNome)
                            .addComponent(lblAutor)
                            .addComponent(lblEditora)
                            .addComponent(lblIsbn)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addGap(15, 15, 15)
                        .addGroup(tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtEditora, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtAutor, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtTitulo, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tabCadastroLayout.createSequentialGroup()
                                    .addGroup(tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(tabCadastroLayout.createSequentialGroup()
                                            .addComponent(txtIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(lblAno))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabCadastroLayout.createSequentialGroup()
                                            .addComponent(txtSerie)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(lblEdicao)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(0, 17, Short.MAX_VALUE))))
                        .addGap(12, 12, 12)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tabCadastroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(boxFornecedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boxDisponibilidade, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(14, 14, 14)
                .addGroup(tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabCadastroLayout.createSequentialGroup()
                        .addGroup(tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12)
                            .addComponent(jLabel7)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(boxCorredor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boxSecao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boxPiso, 0, 1, Short.MAX_VALUE)
                            .addComponent(boxPosicao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane2)
                    .addGroup(tabCadastroLayout.createSequentialGroup()
                        .addGroup(tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabCadastroLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tabCadastroLayout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(jLabel5))
                            .addGroup(tabCadastroLayout.createSequentialGroup()
                                .addGap(160, 160, 160)
                                .addComponent(jLabel4)))
                        .addGap(0, 67, Short.MAX_VALUE))
                    .addGroup(tabCadastroLayout.createSequentialGroup()
                        .addComponent(btnMapa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNovo)))
                .addGroup(tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabCadastroLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18))
                    .addGroup(tabCadastroLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btNavegar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnbaixarCapa))
                    .addGroup(tabCadastroLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lblImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tabCadastroLayout.setVerticalGroup(
            tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabCadastroLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(tabCadastroLayout.createSequentialGroup()
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(173, 173, 173))
                            .addGroup(tabCadastroLayout.createSequentialGroup()
                                .addGroup(tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(tabCadastroLayout.createSequentialGroup()
                                        .addGroup(tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(boxFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8))
                                        .addGap(18, 18, 18)
                                        .addGroup(tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(boxDisponibilidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6)))
                                    .addGroup(tabCadastroLayout.createSequentialGroup()
                                        .addGroup(tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(tabCadastroLayout.createSequentialGroup()
                                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(23, 23, 23)
                                                .addGroup(tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel13)
                                                    .addComponent(boxPiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(boxCorredor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel12))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(boxSecao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel9))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(boxPosicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel7))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(tabCadastroLayout.createSequentialGroup()
                                                .addComponent(lblImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(btNavegar)
                                                    .addComponent(btnbaixarCapa))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnMapa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(48, 48, 48))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabCadastroLayout.createSequentialGroup()
                        .addGroup(tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNome))
                        .addGap(18, 18, 18)
                        .addGroup(tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAutor))
                        .addGap(18, 18, 18)
                        .addGroup(tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEditora))
                        .addGap(18, 18, 18)
                        .addGroup(tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIsbn)
                            .addComponent(txtIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAno)
                            .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(lblEdicao)
                            .addComponent(txtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(txtIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnExcluir)
                                .addComponent(btnSalvar)
                                .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel18))
                        .addGap(32, 32, 32))))
        );

        tabbedFrameF.addTab("Cadastro de livros", tabCadastro);

        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconfinder_Door_enter_entrance_exit_leave_logout_out_quit_4831032.png"))); // NOI18N
        jButton1.setText("FECHAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabbedFrameF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabbedFrameF, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // salvar usuario

        Livro obj = new Livro();
        obj.setTitulo(txtTitulo.getText());
        obj.setAutor(txtAutor.getText());
        obj.setEditora(txtEditora.getText());
        obj.setIsbn(txtIsbn.getText());
        obj.setAno(txtAno.getText());
        obj.setSerie(txtSerie.getText());
        obj.setEdicao(txtEdicao.getText());
        obj.setIdioma(txtIdioma.getText());
        //do tipo fornecedor
        obj.setFornecedor((Fornecedor) boxFornecedor.getSelectedItem()); //cannot cast string to fornecedores error
        obj.setPiso((String) boxPiso.getSelectedItem());
        obj.setCorredor((String) boxCorredor.getSelectedItem());
        obj.setPosicao((String) boxPosicao.getSelectedItem());
        obj.setSecao((String) boxSecao.getSelectedItem());
        try {
            int dispo = Integer.valueOf((String) boxDisponibilidade.getSelectedItem());
            obj.setDisponibilidade(dispo);
        } catch (Exception e) {
            obj.setDisponibilidade((int) boxDisponibilidade.getSelectedItem()); //caso venha em txt combobbox
        }
        obj.setObservacoes(txtAreaObservacoes.getText());

        LivroDao dao = null;
        try {
            dao = new LivroDao();
        } catch (Exception ex) {
            Logger.getLogger(FormLivros.class.getName()).log(Level.SEVERE, null, ex);
        }
//
        if (txtTitulo.getText().isEmpty() || txtAutor.getText().isEmpty()
                || txtIsbn.getText().isEmpty() || txtEditora.getText().isEmpty()
                || txtIdioma.getText().isEmpty() || boxDisponibilidade.getSelectedItem() == null
                || boxSecao == null) {
            JOptionPane.showMessageDialog(null, "Campos  com * são de preenchimento obrigatório!");
        } else {
            // salvar/editar
            if (!(txtId.getText()).equals("")) {
                try {
                    obj.setId(Integer.valueOf(txtId.getText()));
                    dao.alterarLivro(obj);
                } catch (IOException ex) {
                    Logger.getLogger(FormLivros.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                dao.cadastrarLivro(obj);
            }
        }

        //dao.cadastrarLivro(obj);
        new Utilitarios().limpaTela(tabCadastro);
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtPesquisaLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaLivrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisaLivrosActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        try {
            // listar suario pt4
            listarLivros();
        } catch (Exception ex) {
            Logger.getLogger(FormLivros.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowActivated

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // excluir
        Livro obj = new Livro();
        obj.setId(Integer.valueOf(txtId.getText()));
        LivroDao dao = null;
        try {
            dao = new LivroDao();
        } catch (Exception ex) {
            Logger.getLogger(FormLivros.class.getName()).log(Level.SEVERE, null, ex);
        }
        dao.excluirLivro(obj);

    }//GEN-LAST:event_btnExcluirActionPerformed
    //TODO parei aqui
    //@Override


    private void tabelaLivrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaLivrosMouseClicked
        try {
            // tabela quando clicado
            LimpaCampos();
            DefaultTableModel model = (DefaultTableModel) tabelaLivros.getModel();
            int selectedRowIndex = tabelaLivros.getSelectedRow();
            tabbedFrameF.setSelectedIndex(1);
            txtId.setText(model.getValueAt(selectedRowIndex, 0).toString());
            txtTitulo.setText(model.getValueAt(selectedRowIndex, 1).toString());
            txtAutor.setText(model.getValueAt(selectedRowIndex, 2).toString());
            txtEditora.setText(model.getValueAt(selectedRowIndex, 3).toString());
            txtIsbn.setText(model.getValueAt(selectedRowIndex, 4).toString());
            txtAno.setText(model.getValueAt(selectedRowIndex, 5).toString());
            txtSerie.setText(model.getValueAt(selectedRowIndex, 6).toString());
            txtEdicao.setText(model.getValueAt(selectedRowIndex, 7).toString());
            txtIdioma.setText(model.getValueAt(selectedRowIndex, 8).toString());
            //txtFornecedor.setText((String) model.getValueAt(selectedRowIndex, 9));
            boxPiso.addItem((String) model.getValueAt(selectedRowIndex, 10));
            boxCorredor.addItem((String) model.getValueAt(selectedRowIndex, 11));
            boxPosicao.addItem((String) model.getValueAt(selectedRowIndex, 12));
            boxSecao.addItem((String) model.getValueAt(selectedRowIndex, 13));
            boxDisponibilidade.addItem((Integer) model.getValueAt(selectedRowIndex, 14));
            txtAreaObservacoes.setText((String) model.getValueAt(selectedRowIndex, 15));

            LivroDao dao = new LivroDao();
            List<Livro> ListaLivros = dao.buscarLivros();
            boxFornecedor.removeAllItems();
            for (Livro f : ListaLivros) {
                boxFornecedor.addItem(f.getFornecedor()/*.getTipos_de_usuarios()*/);
            }
            boxFornecedor.setSelectedItem(model.getValueAt(selectedRowIndex, 9));

            ImageIcon iconLogo = new ImageIcon("C:\\goldenOwl\\images\\books\\" + txtIsbn.getText());

            lblImagem.setIcon(iconLogo);
        } catch (Exception ex) {
            Logger.getLogger(FormLivros.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tabelaLivrosMouseClicked

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
        LimpaCampos();
        Utilitarios util = new Utilitarios();
        util.limpaTela(tabCadastro);
        boxFornecedor.setSelectedItem(-1);
        boxPiso.setSelectedItem(-1);
        boxCorredor.setSelectedIndex(-1);
        boxPosicao.setSelectedIndex(-1);
        boxSecao.setSelectedIndex(-1);
        txtAreaObservacoes.selectAll();
        txtAreaObservacoes.replaceSelection("");
        //boxDisponibilidade.addItem((String) model.getValueAt(selectedRowIndex, 14));
    }//GEN-LAST:event_btnNovoActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloActionPerformed

    private void btnPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnPesquisarKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_btnPesquisarKeyReleased

    private void txtPesquisaLivrosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaLivrosKeyReleased
        // TODO add your handling code here:
        String nome = "%" + txtPesquisaLivros.getText() + "%";
        LivroDao dao = null;
        try {
            dao = new LivroDao();
        } catch (Exception ex) {
            Logger.getLogger(FormLivros.class.getName()).log(Level.SEVERE, null, ex);
        }
        List<Livro> lista = dao.pesquisarNomeLivros(nome);
        DefaultTableModel dados = (DefaultTableModel) tabelaLivros.getModel();
        dados.setNumRows(0); //limpa/zera pesquisa a cada digitacao
        for (Livro c : lista) {
            dados.addRow(new Object[]{
                c.getId(),
                c.getTitulo(),
                c.getAutor(),
                c.getEditora(),
                c.getIsbn(),
                c.getAno(),
                c.getSerie(),
                c.getEdicao(),
                c.getIdioma(),
                c.getFornecedor().getNome(),
                c.getPiso(),
                c.getCorredor(),
                c.getPosicao(),
                c.getSecao(),
                c.getDisponibilidade(),
                c.getObservacoes()

            });
        }
    }//GEN-LAST:event_txtPesquisaLivrosKeyReleased

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:
        String nome = txtTitulo.getText();
        Livro obj = new Livro();
        LivroDao dao = null;
        try {
            dao = new LivroDao();
        } catch (Exception ex) {
            Logger.getLogger(FormLivros.class.getName()).log(Level.SEVERE, null, ex);
        }
        obj = dao.buscarLivro(nome);
        if (obj.getTitulo() != null) {
            txtId.setText(String.valueOf(obj.getId()));
            txtTitulo.setText(obj.getTitulo());
            txtAutor.setText(obj.getAutor());
            txtEditora.setText(obj.getEditora());
            txtIsbn.setText(obj.getIsbn());
            txtAno.setText(obj.getAno());
            txtSerie.setText(obj.getSerie());
            txtEdicao.setText(obj.getEdicao());
            txtIdioma.setText(obj.getIdioma());
            boxFornecedor.setSelectedItem(obj.getFornecedor());
            boxPiso.setSelectedItem(obj.getPiso());
            boxCorredor.setSelectedItem(obj.getCorredor());
            boxPosicao.setSelectedItem(obj.getPosicao());
            boxSecao.setSelectedItem(obj.getSecao());
            boxDisponibilidade.setSelectedItem(obj.getDisponibilidade());
            txtAreaObservacoes.setText(obj.getObservacoes());

            ImageIcon iconLogo = new ImageIcon("C:\\goldenOwl\\images\\usuarios\\" + txtIsbn.getText());
            lblImagem.setIcon(iconLogo);

        } else {
            JOptionPane.showMessageDialog(null, "Livro não encontrado");
        }

    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void txtIdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdiomaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdiomaActionPerformed

    private void boxCorredorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boxCorredorMouseClicked

        OptionsDao dao = new OptionsDao();
        List<Options> ListaOptions = dao.listarCorredor();
        boxCorredor.removeAllItems();
        ListaOptions.forEach((f) -> {
            boxCorredor.addItem(f.getCorredor());
        });
    }//GEN-LAST:event_boxCorredorMouseClicked

    private void boxPisoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boxPisoMouseClicked
        String boxPisoString = String.valueOf(boxPiso.getSelectedIndex());
        boxPiso.removeAllItems();
        OptionsDao dao = new OptionsDao();
        List<Options> ListaOptions = dao.listarPiso();
        
        for (Options f : ListaOptions) {
            boxPiso.insertItemAt(f.getPiso(), boxPiso.getItemCount());
        }
        boxPiso.setSelectedItem(boxPisoString);
    }//GEN-LAST:event_boxPisoMouseClicked

    private void boxSecaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boxSecaoMouseClicked
        OptionsDao dao = new OptionsDao();
        List<Options> ListaOptions = dao.listarSecao();
        boxSecao.removeAllItems();
        for (Options f : ListaOptions) {
            boxSecao.addItem(f.getSecao());
        }
    }//GEN-LAST:event_boxSecaoMouseClicked

    private void boxPosicaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boxPosicaoMouseClicked
        OptionsDao dao = new OptionsDao();
        List<Options> ListaOptions = dao.listarPosicao();
        boxPosicao.removeAllItems();
        for (Options f : ListaOptions) {
            boxPosicao.addItem(f.getPosicao());
        }
    }//GEN-LAST:event_boxPosicaoMouseClicked

    private void btnMapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMapaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMapaActionPerformed

    private void boxDisponibilidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boxDisponibilidadeMouseClicked
        OptionsDao dao = new OptionsDao();
        List<Options> ListaOptions = dao.listarDisponibilidade();
        boxDisponibilidade.removeAllItems(); //limpa
        for (Options f : ListaOptions) {
            boxDisponibilidade.addItem(f.getDisponibilidade());
        }
    }//GEN-LAST:event_boxDisponibilidadeMouseClicked

    private void btNavegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNavegarActionPerformed

        JFileChooser jfile = new JFileChooser();
        int result = jfile.showSaveDialog(this);
        File selectedFile = jfile.getSelectedFile();
        String filename = selectedFile.getName();
        if (filename.endsWith(".jpg") || filename.endsWith(".JPG") || filename.endsWith(".png") || filename.endsWith(".PNG") || filename.endsWith(".jpeg")) {

            FileNameExtensionFilter filter = new FileNameExtensionFilter("*.image", "jpg", "png");
            jfile.addChoosableFileFilter(filter);
            if (result == JFileChooser.APPROVE_OPTION) {
                File selectedImage = jfile.getSelectedFile();
                String path = selectedImage.getAbsolutePath();
                BufferedImage image;
                try {
                    image = ImageIO.read(selectedImage);
                    ImageIO.write(image, "jpg", new File("C:\\goldenOwl\\images\\books\\" + txtIsbn.getText()));
                } catch (IOException ex) {
                    Logger.getLogger(Image.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    lblImagem.setIcon(ResizeBookImage(path));
                    // imagePathStr = path;

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Image Error" + e.getMessage());
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Por Favor Seleciona um arquivo do tipo Imagem", "Tente Novamente!", 1);
        }
    }//GEN-LAST:event_btNavegarActionPerformed

    private void boxFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boxFornecedorMouseClicked
        String boxFornecedorString = String.valueOf(boxFornecedor.getSelectedIndex());
        boxFornecedor.removeAllItems();
        FornecedorDao dao = new FornecedorDao();
        List<Fornecedor> ListaFornecedor = dao.listarFornecedores();
        for (Fornecedor f : ListaFornecedor) {
            boxFornecedor.insertItemAt(f, boxFornecedor.getItemCount()); // era (f.getNome()) mas precisou soberscrecer mopetodo toString em fornecesdores
        }
        boxFornecedor.setSelectedItem(boxFornecedorString);
    }//GEN-LAST:event_boxFornecedorMouseClicked

    private void tabConsultaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabConsultaUsuariosMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_tabConsultaUsuariosMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLivros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxCorredor;
    private javax.swing.JComboBox boxDisponibilidade;
    private javax.swing.JComboBox boxFornecedor;
    private javax.swing.JComboBox<String> boxPiso;
    private javax.swing.JComboBox<String> boxPosicao;
    private javax.swing.JComboBox<String> boxSecao;
    private javax.swing.JButton btNavegar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnMapa;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnbaixarCapa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblAno;
    private javax.swing.JLabel lblAutor;
    private javax.swing.JLabel lblEdicao;
    private javax.swing.JLabel lblEditora;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JLabel lblIsbn;
    private javax.swing.JLabel lblNome;
    private javax.swing.JPanel tabCadastro;
    private javax.swing.JPanel tabConsultaUsuarios;
    private javax.swing.JTabbedPane tabbedFrameF;
    private javax.swing.JTable tabelaLivros;
    private javax.swing.JFormattedTextField txtAno;
    private javax.swing.JTextArea txtAreaObservacoes;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtEdicao;
    private javax.swing.JTextField txtEditora;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdioma;
    private javax.swing.JFormattedTextField txtIsbn;
    private javax.swing.JTextField txtPesquisaLivros;
    private javax.swing.JTextField txtSerie;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
    //private String imagePathStr;

    //resize book image function
    private ImageIcon ResizeBookImage(String imgPath) { //192x261
        int imageX = 162;
        int imageY = 240;
        lblImagem.setSize(imageX, imageY);

        ImageIcon myImage = new ImageIcon(imgPath);
        Image img = myImage.getImage();
        Image newImage = img.getScaledInstance(lblImagem.getWidth(), lblImagem.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImage);
        return image;
    }

}
