/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.projeto.view;

import br.com.projeto.dao.OptionsDao;
import br.com.projeto.model.Options;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.print.PrintService;
import javax.print.PrintServiceLookup;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Everton Luiz Kozloski - evertonkozloski@hotmail.com
 */
public class FormOptions extends javax.swing.JFrame {

    /**
     * Creates new form formLogin
     */
    public FormOptions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        btnSaveIp = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtIp = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        boxPrinter = new javax.swing.JComboBox<>();
        btnSavePrinter = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtLibraryName = new javax.swing.JTextField();
        btnLibraryAddress = new javax.swing.JButton();
        txtLibraryAddress = new javax.swing.JTextField();
        btnLibraryName = new javax.swing.JButton();
        lblLibraryLogo = new javax.swing.JLabel();
        btnSetLibraryLogo = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtUserDB = new javax.swing.JTextField();
        btnSaveUserDB = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        btnSavePassDB = new javax.swing.JButton();
        txtPassDB = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPiso = new javax.swing.JTextField();
        txtCorredor = new javax.swing.JTextField();
        txtPosicao = new javax.swing.JTextField();
        txtSecao = new javax.swing.JTextField();
        btnAddPiso = new javax.swing.JButton();
        btnAddCorredor = new javax.swing.JButton();
        btnAddPosicao = new javax.swing.JButton();
        btnAddSecao = new javax.swing.JButton();
        boxCorredor = new javax.swing.JComboBox<>();
        boxPiso = new javax.swing.JComboBox();
        boxPosicao = new javax.swing.JComboBox<>();
        boxSecao = new javax.swing.JComboBox<>();
        btnExcluirPiso = new javax.swing.JButton();
        btnApagarCorredor = new javax.swing.JButton();
        btnApagarPosicao = new javax.swing.JButton();
        btnApagarSecao = new javax.swing.JButton();
        btnAddDsiponibilidade = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtDisponibilidade = new javax.swing.JTextField();
        boxDisponibilidade = new javax.swing.JComboBox<>();
        btnApagarDisponibilidade = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtTipos = new javax.swing.JTextField();
        btnAddtipos = new javax.swing.JButton();
        boxTipos = new javax.swing.JComboBox();
        btnExcluirTipos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Opções");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSaveIp.setText("Salvar");
        btnSaveIp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveIpActionPerformed(evt);
            }
        });

        jLabel6.setText("IP ou Url  do Servidor");

        jLabel9.setText("Impressora Padrão:");

        boxPrinter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecione>" }));
        boxPrinter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boxPrinterMouseClicked(evt);
            }
        });

        btnSavePrinter.setText("Salvar");
        btnSavePrinter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavePrinterActionPerformed(evt);
            }
        });

        jLabel10.setText("Nome da Instituição:");

        jLabel11.setText("Endereço da Instituição:");

        txtLibraryName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLibraryNameActionPerformed(evt);
            }
        });

        btnLibraryAddress.setText("Salvar");
        btnLibraryAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibraryAddressActionPerformed(evt);
            }
        });

        btnLibraryName.setText("Salvar");
        btnLibraryName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibraryNameActionPerformed(evt);
            }
        });

        lblLibraryLogo.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, java.awt.Color.darkGray));

        btnSetLibraryLogo.setText("Selecione");
        btnSetLibraryLogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetLibraryLogoActionPerformed(evt);
            }
        });

        jLabel13.setText("Logotipo da Instituição");

        jLabel12.setText("Usuario banco de Dados:");

        btnSaveUserDB.setText("Salvar");
        btnSaveUserDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveUserDBActionPerformed(evt);
            }
        });

        jLabel15.setText("Senha Banco de Dados:");

        btnSavePassDB.setText("Salvar");
        btnSavePassDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavePassDBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txtIp, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSaveIp))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(txtUserDB, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSaveUserDB))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(txtPassDB, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSavePassDB)))
                        .addGap(101, 101, 101)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLibraryLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(boxPrinter, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSavePrinter))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLibraryName, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLibraryAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnSetLibraryLogo))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnLibraryName)
                                    .addComponent(btnLibraryAddress))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLibraryLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtIp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSaveIp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtUserDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSaveUserDB))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(btnSavePassDB)
                            .addComponent(txtPassDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSetLibraryLogo)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(boxPrinter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSavePrinter))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtLibraryName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLibraryName))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtLibraryAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLibraryAddress))))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Geral", jPanel2);

        jLabel2.setText("Piso:");

        jLabel3.setText("Corredor:");

        jLabel4.setText("Posição:");

        jLabel5.setText("Seção:");

        txtSecao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSecaoActionPerformed(evt);
            }
        });

        btnAddPiso.setText("Add");
        btnAddPiso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPisoActionPerformed(evt);
            }
        });

        btnAddCorredor.setText("Add");
        btnAddCorredor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCorredorActionPerformed(evt);
            }
        });

        btnAddPosicao.setText("Add");
        btnAddPosicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPosicaoActionPerformed(evt);
            }
        });

        btnAddSecao.setText("Add");
        btnAddSecao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSecaoActionPerformed(evt);
            }
        });

        boxCorredor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Lista de Corredores>" }));
        boxCorredor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boxCorredorMouseClicked(evt);
            }
        });

        boxPiso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Lista de Pisos>" }));
        boxPiso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boxPisoMouseClicked(evt);
            }
        });

        boxPosicao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Lista de Posições>" }));
        boxPosicao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boxPosicaoMouseClicked(evt);
            }
        });

        boxSecao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Lista de Seções>" }));
        boxSecao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boxSecaoMouseClicked(evt);
            }
        });

        btnExcluirPiso.setText("Apagar");
        btnExcluirPiso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirPisoActionPerformed(evt);
            }
        });

        btnApagarCorredor.setText("Apagar");
        btnApagarCorredor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarCorredorActionPerformed(evt);
            }
        });

        btnApagarPosicao.setText("Apagar");
        btnApagarPosicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarPosicaoActionPerformed(evt);
            }
        });

        btnApagarSecao.setText("Apagar");
        btnApagarSecao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarSecaoActionPerformed(evt);
            }
        });

        btnAddDsiponibilidade.setText("Add");
        btnAddDsiponibilidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDsiponibilidadeActionPerformed(evt);
            }
        });

        jLabel7.setText("Disponibilidade:");

        boxDisponibilidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quantos dias pode ser locado" }));
        boxDisponibilidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boxDisponibilidadeMouseClicked(evt);
            }
        });

        btnApagarDisponibilidade.setText("Apagar");
        btnApagarDisponibilidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarDisponibilidadeActionPerformed(evt);
            }
        });

        jLabel8.setText("Configura para qtos dias o livro pode ser locado ( Zero para Apenas Leitura Interna)");

        jLabel14.setText("Tipo de Usuários:");

        btnAddtipos.setText("Add");
        btnAddtipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddtiposActionPerformed(evt);
            }
        });

        boxTipos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Lista de Tipos de Usuários>" }));
        boxTipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boxTiposMouseClicked(evt);
            }
        });
        boxTipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxTiposActionPerformed(evt);
            }
        });

        btnExcluirTipos.setText("Apagar");
        btnExcluirTipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirTiposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel8))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPiso)
                            .addComponent(txtCorredor)
                            .addComponent(txtPosicao)
                            .addComponent(txtSecao)
                            .addComponent(txtDisponibilidade, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnAddPosicao)
                                .addGap(18, 18, 18)
                                .addComponent(boxPosicao, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnApagarPosicao))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnAddCorredor)
                                .addGap(18, 18, 18)
                                .addComponent(boxCorredor, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnApagarCorredor))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnAddPiso)
                                .addGap(18, 18, 18)
                                .addComponent(boxPiso, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnExcluirPiso))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(btnAddDsiponibilidade)
                                        .addGap(18, 18, 18)
                                        .addComponent(boxDisponibilidade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(btnAddSecao)
                                        .addGap(18, 18, 18)
                                        .addComponent(boxSecao, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnApagarSecao)
                                    .addComponent(btnApagarDisponibilidade))))))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTipos, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAddtipos)
                .addGap(18, 18, 18)
                .addComponent(boxTipos, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExcluirTipos)
                .addGap(48, 48, 48))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(btnAddPiso)
                        .addComponent(boxPiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnExcluirPiso))
                    .addComponent(txtPiso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddCorredor)
                    .addComponent(boxCorredor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnApagarCorredor)
                    .addComponent(txtCorredor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPosicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btnAddPosicao)
                    .addComponent(boxPosicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnApagarPosicao))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAddSecao)
                        .addComponent(txtSecao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(boxSecao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnApagarSecao)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAddDsiponibilidade)
                        .addComponent(boxDisponibilidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnApagarDisponibilidade))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txtDisponibilidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddtipos)
                    .addComponent(boxTipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluirTipos)
                    .addComponent(txtTipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Biblioteca", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSecaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSecaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSecaoActionPerformed

    private void btnAddSecaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSecaoActionPerformed
        Options obj = new Options();
        obj.setSecao(txtSecao.getText());
        OptionsDao dao = new OptionsDao();
        dao.cadastrarSecao(obj);
    }//GEN-LAST:event_btnAddSecaoActionPerformed

    // botao excluir corredor
    private void btnApagarCorredorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarCorredorActionPerformed
        Options obj = new Options();
        obj.setCorredor((String) boxCorredor.getSelectedItem());// aqui
        OptionsDao dao = new OptionsDao();
        dao.excluirCorredor(obj);
    }//GEN-LAST:event_btnApagarCorredorActionPerformed

    // botao add piso
    private void btnAddPisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPisoActionPerformed
        Options obj = new Options();
        obj.setPiso(txtPiso.getText());
        OptionsDao dao = new OptionsDao();
        dao.cadastrarPiso(obj);
    }//GEN-LAST:event_btnAddPisoActionPerformed

    //combobox Piso
    private void boxPisoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boxPisoMouseClicked
        OptionsDao dao = new OptionsDao();
        List<Options> ListaOptions = dao.listarPiso();
        boxPiso.removeAllItems();
        for (Options f : ListaOptions) {
            boxPiso.addItem(f.getPiso());
        }
    }//GEN-LAST:event_boxPisoMouseClicked

    //botao excluir piso
    private void btnExcluirPisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirPisoActionPerformed
        Options obj = new Options();
        obj.setPiso((String) boxPiso.getSelectedItem());// aqui
        OptionsDao dao = new OptionsDao();
        dao.excluirPiso(obj);
    }//GEN-LAST:event_btnExcluirPisoActionPerformed

    //botao add corredor
    private void btnAddCorredorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCorredorActionPerformed
        Options obj = new Options();
        obj.setCorredor(txtCorredor.getText());
        OptionsDao dao = new OptionsDao();
        dao.cadastrarCorredor(obj);
    }//GEN-LAST:event_btnAddCorredorActionPerformed

    // combobox corredor
    private void boxCorredorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boxCorredorMouseClicked
        OptionsDao dao = new OptionsDao();
        List<Options> ListaOptions = dao.listarCorredor();
        boxCorredor.removeAllItems();
        for (Options f : ListaOptions) {
            boxCorredor.addItem(f.getCorredor());
        }
    }//GEN-LAST:event_boxCorredorMouseClicked

    private void btnAddPosicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPosicaoActionPerformed
        Options obj = new Options();
        obj.setPosicao(txtPosicao.getText());
        OptionsDao dao = new OptionsDao();
        dao.cadastrarPosicao(obj);
    }//GEN-LAST:event_btnAddPosicaoActionPerformed

    private void boxPosicaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boxPosicaoMouseClicked
        OptionsDao dao = new OptionsDao();
        List<Options> ListaOptions = dao.listarPosicao();
        boxPosicao.removeAllItems();
        for (Options f : ListaOptions) {
            boxPosicao.addItem(f.getPosicao());
        }
    }//GEN-LAST:event_boxPosicaoMouseClicked

    private void btnApagarPosicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarPosicaoActionPerformed
        Options obj = new Options();
        obj.setPosicao((String) boxPosicao.getSelectedItem());// aqui
        OptionsDao dao = new OptionsDao();
        dao.excluirPosicao(obj);
    }//GEN-LAST:event_btnApagarPosicaoActionPerformed

    private void boxSecaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boxSecaoMouseClicked
        OptionsDao dao = new OptionsDao();
        List<Options> ListaOptions = dao.listarSecao();
        boxSecao.removeAllItems();
        for (Options f : ListaOptions) {
            boxSecao.addItem(f.getSecao());
        }
    }//GEN-LAST:event_boxSecaoMouseClicked

    private void btnApagarSecaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarSecaoActionPerformed
        Options obj = new Options();
        obj.setSecao((String) boxSecao.getSelectedItem());// aqui
        OptionsDao dao = new OptionsDao();
        dao.excluirSecao(obj);
    }//GEN-LAST:event_btnApagarSecaoActionPerformed

    private void btnAddDsiponibilidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDsiponibilidadeActionPerformed
        Options obj = new Options();
        obj.setDisponibilidade(txtDisponibilidade.getText());
        OptionsDao dao = new OptionsDao();
        dao.cadastrarDisponibilidade(obj);
    }//GEN-LAST:event_btnAddDsiponibilidadeActionPerformed

    private void boxDisponibilidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boxDisponibilidadeMouseClicked
        OptionsDao dao = new OptionsDao();
        List<Options> ListaOptions = dao.listarDisponibilidade();
        boxDisponibilidade.removeAllItems();
        for (Options f : ListaOptions) {
            boxDisponibilidade.addItem(f.getDisponibilidade());
        }
    }//GEN-LAST:event_boxDisponibilidadeMouseClicked

    private void btnApagarDisponibilidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarDisponibilidadeActionPerformed
        Options obj = new Options();
        obj.setDisponibilidade((String) boxDisponibilidade.getSelectedItem());// aqui
        OptionsDao dao = new OptionsDao();
        dao.excluirDisponibilidade(obj);
    }//GEN-LAST:event_btnApagarDisponibilidadeActionPerformed

    private void txtLibraryNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLibraryNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLibraryNameActionPerformed

    private void btnAddtiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddtiposActionPerformed
        Options obj = new Options();
        obj.setTipos_de_usuarios(txtTipos.getText());
        OptionsDao dao = new OptionsDao();
        dao.cadastrarTipos_de_usuarios(obj);
    }//GEN-LAST:event_btnAddtiposActionPerformed

    private void boxTiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boxTiposMouseClicked
        OptionsDao dao = new OptionsDao();
        List<Options> ListaOptions = dao.listarTipos_de_usuarios();
        boxTipos.removeAllItems();
        for (Options f : ListaOptions) {
            boxTipos.addItem(f.getTipos_de_usuarios());
        }
    }//GEN-LAST:event_boxTiposMouseClicked

    private void btnExcluirTiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirTiposActionPerformed
        Options obj = new Options();
        obj.setTipos_de_usuarios((String) boxTipos.getSelectedItem());// aqui
        OptionsDao dao = new OptionsDao();
        dao.excluirTipos_de_usuarios(obj);

    }//GEN-LAST:event_btnExcluirTiposActionPerformed

    private void boxTiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxTiposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxTiposActionPerformed

    private void btnSaveIpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveIpActionPerformed

        try {
            //mudar para dao com esse     
            PrintWriter out = new PrintWriter(new FileWriter("C:\\GoldenOwl\\ipserver"));
            //txtIp.getText();
            txtIp.write(out);
        } catch (IOException e1) {
            System.err.println("Error occurred");
            e1.printStackTrace();
        }
        //editar
        //mostrar ip no inicio
        try {
            Options obj = new Options();
            obj.setServer_ip((String) txtIp.getText());// aqui
            OptionsDao dao = new OptionsDao();
            dao.setIp(obj);
            JOptionPane.showMessageDialog(null, "Ip Salvo!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro:" + e);
        }
    }//GEN-LAST:event_btnSaveIpActionPerformed


    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

        //impressoas padrão aqui
        OptionsDao op = new OptionsDao();
        try {
            //pegar pela campo de parent_id
            txtLibraryName.setText(op.retornaOption(15));
            txtLibraryAddress.setText(op.retornaOption(16));
            //set txtUserDB content at startup
            String content;
            content = new String(Files.readAllBytes(Paths.get("C:\\GoldenOwl\\DBUser")));
            txtUserDB.setText(content);
        } catch (SQLException ex) {
            Logger.getLogger(FormOptions.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(FormOptions.class.getName()).log(Level.SEVERE, null, ex);
        }
        //set ipserver txt
        String contentUser = null;
        try {
            contentUser = new String(Files.readAllBytes(Paths.get("C:\\GoldenOwl\\ipserver")));
        } catch (IOException ex) {
            Logger.getLogger(FormOptions.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtIp.setText(contentUser);

        String contentPAss = null;
        try {
            contentPAss = new String(Files.readAllBytes(Paths.get("C:\\GoldenOwl\\DBPass")));
        } catch (IOException ex) {
            Logger.getLogger(FormOptions.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtPassDB.setText(contentPAss);

        //imagem logotipo mostrando aqui
        String path = "C:\\goldenOwl\\images\\libraryLogo.png";
        lblLibraryLogo.setIcon(ResizeLibraryLogoImage(path));

    }//GEN-LAST:event_formWindowActivated

    private void btnSetLibraryLogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetLibraryLogoActionPerformed
        JFileChooser jfile = new JFileChooser();
        int result = jfile.showSaveDialog(this);
        File selectedFile = jfile.getSelectedFile();
        String filename = selectedFile.getName();
        if (filename.endsWith(".png") || filename.endsWith(".PNG")) {
            FileNameExtensionFilter filter = new FileNameExtensionFilter("*.image", "png");
            jfile.addChoosableFileFilter(filter);
            if (result == JFileChooser.APPROVE_OPTION) {
                File selectedImage = jfile.getSelectedFile();
                String path = selectedImage.getAbsolutePath();
                BufferedImage image;
                try {
                    image = ImageIO.read(selectedImage);
                    ImageIO.write(image, "png", new File("C:\\goldenOwl\\images\\" + "libraryLogo.png"));
                } catch (IOException ex) {
                    Logger.getLogger(Image.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    lblLibraryLogo.setIcon(ResizeLibraryLogoImage(path));
                    // imagePathStr = path;

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Image Error" + e.getMessage());
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Por Favor Seleciona um arquivo do tipo png", "Tente Novamente!", 1);
        }
    }//GEN-LAST:event_btnSetLibraryLogoActionPerformed

    private void btnLibraryNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibraryNameActionPerformed
        try {
            Options obj = new Options();
            obj.setLibrary_name((String) txtLibraryName.getText());// aqui
            OptionsDao dao = new OptionsDao();
            dao.setLibraryName(obj);
            JOptionPane.showMessageDialog(null, "Registro  Salvo!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro:" + e);
        }
    }//GEN-LAST:event_btnLibraryNameActionPerformed

    private void btnLibraryAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibraryAddressActionPerformed

        try {
            Options obj = new Options();
            obj.setLibrary_name((String) txtLibraryAddress.getText());// aqui
            OptionsDao dao = new OptionsDao();
            dao.setLibraryAddress(obj);
            JOptionPane.showMessageDialog(null, "Registro  Salvo!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro:" + e);
        }
    }//GEN-LAST:event_btnLibraryAddressActionPerformed

    private void btnSaveUserDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveUserDBActionPerformed
        try {
            //mudar para dao com esse     
            PrintWriter out = new PrintWriter(new FileWriter("C:\\GoldenOwl\\DBUser"));
            //txtIp.getText();
            txtUserDB.write(out);
        } catch (IOException e1) {
            System.err.println("Error occurred");
            e1.printStackTrace();
        }
        //gravar no db?

//                try {
//            Options obj = new Options();
//        obj.setServer_ip((String) txtUserDB.getText());// aqui
//        OptionsDao dao = new OptionsDao();
//        dao.setIp(obj); 
//            JOptionPane.showMessageDialog(null, "Ip Salvo!");
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "Erro:"+ e);
//        }
    }//GEN-LAST:event_btnSaveUserDBActionPerformed

    private void btnSavePassDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavePassDBActionPerformed
        try {
            //mudar para dao com esse     
            PrintWriter out = new PrintWriter(new FileWriter("C:\\GoldenOwl\\DBPass"));
            //txtIp.getText();
            txtPassDB.write(out);
        } catch (IOException e1) {
            System.err.println("Error occurred");
            e1.printStackTrace();
        }
    }//GEN-LAST:event_btnSavePassDBActionPerformed

    private void boxPrinterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boxPrinterMouseClicked
        PrintService[] printServices = PrintServiceLookup.lookupPrintServices(null, null);
        for (PrintService printer : printServices) {
            boxPrinter.addItem(printer.getName());
        }
    }//GEN-LAST:event_boxPrinterMouseClicked

    private void btnSavePrinterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavePrinterActionPerformed
        try {
            //mudar para dao com esse     
            PrintWriter out = new PrintWriter(new FileWriter("C:\\GoldenOwl\\DefaultPrinter"));
            String printer = (String) boxPrinter.getSelectedItem();
            System.out.println(printer);
            out.println(printer);
            out.close();
        } catch (IOException e1) {
            System.err.println("Error occurred");
            e1.printStackTrace();
        }
    }//GEN-LAST:event_btnSavePrinterActionPerformed

    //############################################################################
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormOptions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxCorredor;
    private javax.swing.JComboBox<String> boxDisponibilidade;
    private javax.swing.JComboBox boxPiso;
    private javax.swing.JComboBox<String> boxPosicao;
    private javax.swing.JComboBox<String> boxPrinter;
    private javax.swing.JComboBox<String> boxSecao;
    private javax.swing.JComboBox boxTipos;
    private javax.swing.JButton btnAddCorredor;
    private javax.swing.JButton btnAddDsiponibilidade;
    private javax.swing.JButton btnAddPiso;
    private javax.swing.JButton btnAddPosicao;
    private javax.swing.JButton btnAddSecao;
    private javax.swing.JButton btnAddtipos;
    private javax.swing.JButton btnApagarCorredor;
    private javax.swing.JButton btnApagarDisponibilidade;
    private javax.swing.JButton btnApagarPosicao;
    private javax.swing.JButton btnApagarSecao;
    private javax.swing.JButton btnExcluirPiso;
    private javax.swing.JButton btnExcluirTipos;
    private javax.swing.JButton btnLibraryAddress;
    private javax.swing.JButton btnLibraryName;
    private javax.swing.JButton btnSaveIp;
    private javax.swing.JButton btnSavePassDB;
    private javax.swing.JButton btnSavePrinter;
    private javax.swing.JButton btnSaveUserDB;
    private javax.swing.JButton btnSetLibraryLogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lblLibraryLogo;
    private javax.swing.JTextField txtCorredor;
    private javax.swing.JTextField txtDisponibilidade;
    private javax.swing.JTextField txtIp;
    private javax.swing.JTextField txtLibraryAddress;
    private javax.swing.JTextField txtLibraryName;
    private javax.swing.JPasswordField txtPassDB;
    private javax.swing.JTextField txtPiso;
    private javax.swing.JTextField txtPosicao;
    private javax.swing.JTextField txtSecao;
    private javax.swing.JTextField txtTipos;
    private javax.swing.JTextField txtUserDB;
    // End of variables declaration//GEN-END:variables
private ImageIcon ResizeLibraryLogoImage(String imgPath) { //192x261
        int imageX = 143;
        int imageY = 146;
        lblLibraryLogo.setSize(imageX, imageY);

        ImageIcon myImage = new ImageIcon(imgPath);
        Image img = myImage.getImage();
        Image newImage = img.getScaledInstance(lblLibraryLogo.getWidth(), lblLibraryLogo.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImage);
        return image;
    }

}
